### ISSUE TITLE
Hawkshaw

### ISSUE THREAD

**Issue by saksham2410** [wishihab/Android-RATList#2]
Please have a look at Hawkshaw :-

https://hawkshaw.tk

Features :-

Optimised for android 9!
Fully Hidden
Camera
Storage
SMS
CALL
Whatsapp Reader
Instagram Reader
Messenger Reader
Gmail Reader
Tinder Reader
Contact
Browser History
App Manager
GPS Location
Microphone
Do a toast
Send a text message
Give call
Open an URL in the default browser
Do vibrate the phone
Explore Files with full access.

Web Interface also available :-

![WhatsApp Image 2019-09-15 at 1 50 51 AM (1)](https://user-images.githubusercontent.com/23457488/65230198-09513f00-daeb-11e9-8813-55d49d3b6206.jpeg)

![WhatsApp Image 2019-09-15 at 1 50 51 AM](https://user-images.githubusercontent.com/23457488/65230215-1110e380-daeb-11e9-943f-418e67f5159e.jpeg)

![WhatsApp Image 2019-09-15 at 1 50 50 AM](https://user-images.githubusercontent.com/23457488/65230222-140bd400-daeb-11e9-95de-f7509243dcf8.jpeg)

**Comment by wishihab** [comment]
Thanks dude, lemme check
