### ISSUE TITLE
please add some extra info 

### ISSUE THREAD

**Issue by graysuit** [wishihab/Android-RATList#4]
Respected @wishihab, 

Impressive repo !
Repo can be improved by specifying extra details like:
```
XXXX1 RAT:
- Requires port forwarding: no
- Have GUI controller : yes
- Platform specific controller: no (web based, can be used anywhere)

XXXX2 RAT:
- Requires port forwarding: yes
- Have GUI controller : no (command line)
- Platform specific controller: yes (only for windows)
```
And also its better you use `table` instead of `list`.

Regards & Thanks so much for the free and needed repo.

**Comment by wishihab** [comment]
Hi @graysuit glad to know you add some issues.

Sounds good idea, well I'm gonna do that when have a time to maintain the repo.
Thank you

**Comment by graysuit** [comment]
Currently I see some RATs are not available or paid or old.
So its good idea to review whole repo and keep this issue open till TODO is completed.
Thanks sir.

**Comment by wishihab** [comment]
Well if you have time to help me or show me the example of tables, you can send pull request..
I tryin my best to help people know about this kind virus 😃

**Comment by 12JHONWICK** [comment]
Does it work for Android version 10

**Comment by wishihab** [comment]
> Does it work for Android version 10

Hi, AhMyth work for android 10 but not fully function. You can try all the downloadable RAT builder.
But I recommend TheFatRAT

**Comment by wishihab** [comment]
hi graysuit, I'm going to update readme.md soon.

Thankyou
